# Generated by Django 4.2.7 on 2023-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_id", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_spending_on_ads", models.BooleanField(default=False)),
                ("reviews", models.IntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True, max_length=1024)),
                ("featured_image", models.URLField(blank=True, max_length=1024)),
                ("main_category", models.CharField(blank=True, max_length=255)),
                ("categories", models.JSONField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("workday_timing", models.CharField(blank=True, max_length=255)),
                ("closed_on", models.JSONField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=1024)),
                ("review_keywords", models.JSONField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=1024)),
                ("owner", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
