# Generated by Django 4.2.7 on 2023-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_alter_laboratory_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboratory",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="postal_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
